/**
 * L0 bundled starter deck — hand-authored, ships with the application, always available
 * (spec §07 cache hierarchy). This is the deck that makes the party start instantly
 * with zero inference. Expanded decks land in later PRs.
 */

import type { Card } from "./types.js";

export const STARTER_DECK: Card[] = [
  {
    id: "sl-mov-001",
    secret: "Jurassic Park",
    aliases: ["Jurassic", "Jurassic Park movie"],
    category: "Movies",
    forbidden: ["dinosaur", "movie", "island", "park"],
    budget: 5,
    difficulty: 2,
    revealLine: "They spared no expense. You spared no comprehension.",
  },
  {
    id: "sl-mov-002",
    secret: "Titanic",
    aliases: ["the Titanic"],
    category: "Movies",
    forbidden: ["ship", "iceberg", "sink", "boat"],
    budget: 5,
    difficulty: 1,
    revealLine: "There was room on that door and room in that clue.",
  },
  {
    id: "sl-fam-001",
    secret: "Thanksgiving",
    aliases: ["Thanksgiving Day"],
    category: "Family",
    forbidden: ["turkey", "november", "holiday", "dinner"],
    budget: 5,
    difficulty: 1,
    revealLine: "Okay… that was technically a clue.",
  },
  {
    id: "sl-fam-002",
    secret: "Group chat",
    aliases: ["the group chat"],
    category: "Family",
    forbidden: ["text", "phone", "message", "family"],
    budget: 4,
    difficulty: 2,
    revealLine: "Someone here is definitely muting it tonight.",
  },
  {
    id: "sl-mus-001",
    secret: "Karaoke",
    aliases: ["karaoke night"],
    category: "Music",
    forbidden: ["sing", "microphone", "bar", "song"],
    budget: 4,
    difficulty: 2,
    revealLine: "Confidence: 100. Pitch: unaccounted for.",
  },
  {
    id: "sl-pop-001",
    secret: "Selfie",
    aliases: ["selfies"],
    category: "Pop Culture",
    forbidden: ["photo", "camera", "phone", "picture"],
    budget: 3,
    difficulty: 2,
    revealLine: "Front-facing evidence of a good time.",
  },
  {
    id: "sl-pop-002",
    secret: "Road trip",
    aliases: ["roadtrip"],
    category: "Pop Culture",
    forbidden: ["car", "drive", "highway", "travel"],
    budget: 4,
    difficulty: 1,
    revealLine: "Are we there yet? The clue certainly wasn't.",
  },
  {
    id: "sl-mov-003",
    secret: "Home Alone",
    aliases: ["Home Alone movie"],
    category: "Movies",
    forbidden: ["kevin", "christmas", "burglar", "house"],
    budget: 4,
    difficulty: 2,
    revealLine: "The clue screamed. So did everyone else.",
  },
  {
    id: "sl-fam-003",
    secret: "Leftovers",
    aliases: ["the leftovers"],
    category: "Family",
    forbidden: ["food", "fridge", "tupperware", "dinner"],
    budget: 3,
    difficulty: 3,
    revealLine: "Tonight's winner: whoever called dibs first.",
  },
  {
    id: "sl-mus-002",
    secret: "Air guitar",
    aliases: ["air guitar solo"],
    category: "Music",
    forbidden: ["instrument", "pretend", "rock", "invisible"],
    budget: 3,
    difficulty: 3,
    revealLine: "Zero strings attached.",
  },
  {
    id: "sl-pop-003",
    secret: "Wifi password",
    aliases: ["the wifi password", "wifi code"],
    category: "Pop Culture",
    forbidden: ["internet", "router", "network", "connect"],
    budget: 3,
    difficulty: 3,
    revealLine: "The true test of any friendship.",
  },
  {
    id: "sl-fam-004",
    secret: "Inside joke",
    aliases: ["inside jokes"],
    category: "Family",
    forbidden: ["funny", "secret", "laugh", "joke"],
    budget: 1,
    difficulty: 4,
    revealLine: "You had to be there. Now you are.",
  },
];
